### ISSUE TITLE
getInteractionGroupTree TypeError

### ISSUE THREAD

**Issue by Marantesss** [OwenCalvin/discord.ts#69]
Whenever I try to tun a simple slash command, I get a `TypeError` in the `getInteractionGroupTree(interaction)` method.

### Error Stack

```
(node:13002) DeprecationWarning: The interaction event is deprecated. Use interactionCreate instead
(Use `node --trace-deprecation ...` to show where the warning was created)
internal/process/warning:50
TypeError: _a.values is not a function
    at getOptionsTree (/home/marantesss/Documents/marantilhas/node_modules/@typeit/src/Client.ts:296:58)
    at Client.getInteractionGroupTree (/home/marantesss/Documents/marantilhas/node_modules/@typeit/src/Client.ts:300:5)
    at Client.executeSlash (/home/marantesss/Documents/marantilhas/node_modules/@typeit/src/Client.ts:362:23)
    at Client.<anonymous> (/home/marantesss/Documents/marantilhas/src/App.ts:41:12)
    ...
```

### Debug screenshot

![image](https://user-images.githubusercontent.com/36729905/132850337-b3ca7540-5926-4a2b-a594-07f7dda26630.png)

### Node version

I'm actually using `nvm` to manage my node versions. But both my default and debug versions are `16.9.0`.

### My `package.json`

```json
"scripts": {
    "dev": "nodemon --config nodemon.json src/App.ts",
    "build": "tsc",
    "start": "node dist/App.js",
    "lint": "eslint src/.",
    "test": "echo 'Your tests are in another castle 🏰'"
  },
  "dependencies": {
    "@typeit/discord": "^5.0.13",
    "discord.js": "^13.1.0",
    "dotenv": "^10.0.0",
    "reflect-metadata": "^0.1.13"
  },
  "devDependencies": {
    "@types/node": "^16.7.13",
    "@typescript-eslint/eslint-plugin": "^4.31.0",
    "@typescript-eslint/parser": "^4.31.0",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "nodemon": "^2.0.12",
    "prettier": "^2.3.2",
    "ts-node": "^10.2.1",
    "tslib": "^2.3.1",
    "typescript": "^4.4.2"
  }
```

**Comment by Marantesss** [comment]
From reading the other issues I've just found out that this package is no longer maintained :cry: 

It might be a good idea to put up a disclaimer or something.

**Comment by VictoriqueMoe** [comment]
> From reading the other issues I've just found out that this package is no longer maintained :cry: 
> 
> It might be a good idea to put up a disclaimer or something.

https://github.com/oceanroleplay/discord.ts
