### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ArcheoCodix** [OwenCalvin/discord.ts#8]
Hello,

Thank you for your library, I like TS.
When I run Main.js, this error occur (I try on your example) : 
command line : node Main.js
discord.ts-master/examples/commandsDir/build/discords/DiscordApp.d.ts:1
import { CommandMessage } from '@typeit/discord';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:983:16)
    at Module._compile (internal/modules/cjs/loader.js:1033:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at ~/discord.ts-master/examples/commandsDir/node_modules/@typeit/discord/Client.js:81:25
    at Array.map (<anonymous>)
    at ~/discord.ts-master/examples/commandsDir/node_modules/@typeit/discord/Client.js:80:27

**Comment by OwenCalvin** [comment]
I think that you might have this error because you didn't setup the project correctly, can you join the Discord server ? Je serais ravis de pouvoir mieux t'aider :)
https://discord.gg/sh48jtW
